version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/local/mysql/data
    expose:
      - "3307"
    ports:
      - "3307:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=postman

  file-processor-app:
    build: .
    image: large-file-processor-app
    container_name: large-file-processor-app
    hostname: file-processor-app
    tty: true
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local